FROM node:16-alpine

WORKDIR '/app'

COPY package.json .
RUN npm install

# We can delete it by using docker volumes in the run command or docker-compose.yml. 
# Even if we can delete it, we should still keep it there.
COPY . .

CMD ["npm", "run", "start"]