version: '3'
services:
  react-app:
    build: 
      # Where we want the images to come from
      context: . # if we had nested files we'd look into that nested folder
      # Location of docker file that will be used
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - .:/app
  tests:
    build: 
      # Where we want the images to come from
      context: . # if we had nested files we'd look into that nested folder
      # Location of docker file that will be used
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - .:/app
    command: ["npm", "run", "test"]